package pe.com.igastronomico.model;
// Generated 05/07/2010 12:21:34 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * CategoriaCosto generated by hbm2java
 */
public class CategoriaCosto  implements java.io.Serializable {


     private Integer idcategoriaCosto;
     private String categoriaCosto;

    public CategoriaCosto() {
    }

    public CategoriaCosto(String categoriaCosto) {
       this.categoriaCosto = categoriaCosto;
    }
   
    public Integer getIdcategoriaCosto() {
        return this.idcategoriaCosto;
    }
    
    public void setIdcategoriaCosto(Integer idcategoriaCosto) {
        this.idcategoriaCosto = idcategoriaCosto;
    }
    public String getCategoriaCosto() {
        return this.categoriaCosto;
    }
    
    public void setCategoriaCosto(String categoriaCosto) {
        this.categoriaCosto = categoriaCosto;
    }

    public String toString(){
        return categoriaCosto;
    }

}


