package pe.com.igastronomico.model;
// Generated 05/07/2010 12:21:34 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * TipoUsuario generated by hbm2java
 */
public class TipoUsuario  implements java.io.Serializable {


     private Integer idtipoUsuario;
     private String tipoUsuario;

    public TipoUsuario() {
    }

    public TipoUsuario(String tipoUsuario) {
       this.tipoUsuario = tipoUsuario;       
    }
   
    public Integer getIdtipoUsuario() {
        return this.idtipoUsuario;
    }
    
    public void setIdtipoUsuario(Integer idtipoUsuario) {
        this.idtipoUsuario = idtipoUsuario;
    }
    public String getTipoUsuario() {
        return this.tipoUsuario;
    }
    
    public void setTipoUsuario(String tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }

    public String toString(){
        return this.getTipoUsuario();
    }
}


