package pe.com.igastronomico.model;
// Generated 05/07/2010 12:21:34 PM by Hibernate Tools 3.2.1.GA

import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer codUsuario;
     private String loginUsuario;
     private String claveUsuario;
     private TipoUsuario tipoUsuario;
     private String nombreUsuario;
     private Date fechaRegistro;
     private Set comentarios = new HashSet(0);
     private Set locals = new HashSet(0);
     private Set tours = new HashSet(0);
     private byte[] fotoUsuario;

    public Usuario() {
        this.fechaRegistro = new Date();
    }

    public Usuario(TipoUsuario tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }

    public Usuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }

    public Usuario(TipoUsuario tipoUsuario, String nombreUsuario, Date fechaRegistro, Set comentarios, Set locals, Set tours, String loginUsuario, String claveUsuario) {
       this.tipoUsuario = tipoUsuario;
       this.nombreUsuario = nombreUsuario;
       this.fechaRegistro = fechaRegistro;
       this.comentarios = comentarios;
       this.locals = locals;
       this.tours = tours;
       this.loginUsuario=loginUsuario;
       this.claveUsuario=claveUsuario;
    }
   
    public Integer getCodUsuario() {
        return this.codUsuario;
    }
    
    public void setCodUsuario(Integer codUsuario) {
        this.codUsuario = codUsuario;
    }
    public TipoUsuario getTipoUsuario() {
        return this.tipoUsuario;
    }
    
    public void setTipoUsuario(TipoUsuario tipoUsuario) {
        this.tipoUsuario = tipoUsuario;
    }
    public String getNombreUsuario() {
        return this.nombreUsuario;
    }
    
    public void setNombreUsuario(String nombreUsuario) {
        this.nombreUsuario = nombreUsuario;
    }
    public Date getFechaRegistro() {
        return this.fechaRegistro;
    }
    
    public void setFechaRegistro(Date fechaRegistro) {
        this.fechaRegistro = fechaRegistro;
    }
    public Set getComentarios() {
        return this.comentarios;
    }
    
    public void setComentarios(Set comentarios) {
        this.comentarios = comentarios;
    }
    public Set getLocals() {
        return this.locals;
    }
    
    public void setLocals(Set locals) {
        this.locals = locals;
    }
    public Set getTours() {
        return this.tours;
    }

    
    public void setTours(Set tours) {
        this.tours = tours;
    }


    public String getClaveUsuario() {
        return claveUsuario;
    }


    public void setClaveUsuario(String claveUsuario) {
        this.claveUsuario = claveUsuario;
    }


    public String getLoginUsuario() {
        return loginUsuario;
    }


    public void setLoginUsuario(String loginUsuario) {
        this.loginUsuario = loginUsuario;
    }


    public byte[] getFotoUsuario() {
        return fotoUsuario;
    }


    public void setFotoUsuario(byte[] fotoUsuario) {
        this.fotoUsuario = fotoUsuario;
    }


    public boolean isNew() {
	return (this.codUsuario == null);
    }

}


