package pe.com.igastronomico.model;
// Generated 05/07/2010 12:21:34 PM by Hibernate Tools 3.2.1.GA



/**
 * Comentario generated by hbm2java
 */
public class Comentario  implements java.io.Serializable {


     private Integer idcomentario;
     private Local local;
     private Usuario usuario;
     private String comentario;
     private Integer calificacion;

    public Comentario() {
    }

	
    public Comentario(Local local, Usuario usuario) {
        this.local = local;
        this.usuario = usuario;
    }
    public Comentario(Local local, Usuario usuario, String comentario, Integer calificacion) {
       this.local = local;
       this.usuario = usuario;
       this.comentario = comentario;
       this.calificacion = calificacion;
    }
   
    public Integer getIdcomentario() {
        return this.idcomentario;
    }
    
    public void setIdcomentario(Integer idcomentario) {
        this.idcomentario = idcomentario;
    }
    public Local getLocal() {
        return this.local;
    }
    
    public void setLocal(Local local) {
        this.local = local;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getComentario() {
        return this.comentario;
    }
    
    public void setComentario(String comentario) {
        this.comentario = comentario;
    }
    public Integer getCalificacion() {
        return this.calificacion;
    }
    
    public void setCalificacion(Integer calificacion) {
        this.calificacion = calificacion;
    }




}


