package pe.com.igastronomico.model;
// Generated 05/07/2010 12:21:34 PM by Hibernate Tools 3.2.1.GA


import java.util.HashSet;
import java.util.Set;

/**
 * Local generated by hbm2java 
 */
public class Local  implements java.io.Serializable {


     private Integer codLocal;
     private CategoriaCosto categoriaCosto;
     private CategoriaPlato categoriaPlato;
     private Usuario usuario;
     private String razonSocial;
     private String departamento;
     private String provincia;
     private String distrito;
     private String direccion;
     private String referencia;
     private String personaDeContacto;
     private String telefonos;
     private String correo;
     private String web;
     private byte[] fotoLocal;
     private byte[] fotoUbicacion;
     private Integer flagPromocion;
     private String comentarioPerfil;
     private String cartaActual;
     private String promocionActual;
     private Set comentarios = new HashSet(0);
     private Set tours = new HashSet(0);

    public Local() {
    }

	
    public Local(CategoriaCosto categoriaCosto, CategoriaPlato categoriaPlato, Usuario usuario) {
        this.categoriaCosto = categoriaCosto;
        this.categoriaPlato = categoriaPlato;
        this.usuario = usuario;
    }
    public Local(CategoriaCosto categoriaCosto, CategoriaPlato categoriaPlato, Usuario usuario, String razonSocial, String departamento, String provincia, String distrito, String direccion, String referencia, String personaDeContacto, String telefonos, String correo, String web, byte[] fotoLocal, byte[] fotoUbicacion, Integer flagPromocion, String comentarioPerfil, String cartaActual, String promocionActual, Set comentarios, Set tours) {
       this.categoriaCosto = categoriaCosto;
       this.categoriaPlato = categoriaPlato;
       this.usuario = usuario;
       this.razonSocial = razonSocial;
       this.departamento = departamento;
       this.provincia = provincia;
       this.distrito = distrito;
       this.direccion = direccion;
       this.referencia = referencia;
       this.personaDeContacto = personaDeContacto;
       this.telefonos = telefonos;
       this.correo = correo;
       this.web = web;
       this.fotoLocal = fotoLocal;
       this.fotoUbicacion = fotoUbicacion;
       this.flagPromocion = flagPromocion;
       this.comentarioPerfil = comentarioPerfil;
       this.cartaActual = cartaActual;
       this.promocionActual = promocionActual;
       this.comentarios = comentarios;
       this.tours = tours;
    }
   
    public Integer getCodLocal() {
        return this.codLocal;
    }
    
    public void setCodLocal(Integer codLocal) {
        this.codLocal = codLocal;
    }
    public CategoriaCosto getCategoriaCosto() {
        return this.categoriaCosto;
    }
    
    public void setCategoriaCosto(CategoriaCosto categoriaCosto) {
        this.categoriaCosto = categoriaCosto;
    }
    public CategoriaPlato getCategoriaPlato() {
        return this.categoriaPlato;
    }
    
    public void setCategoriaPlato(CategoriaPlato categoriaPlato) {
        this.categoriaPlato = categoriaPlato;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public String getRazonSocial() {
        return this.razonSocial;
    }
    
    public void setRazonSocial(String razonSocial) {
        this.razonSocial = razonSocial;
    }
    public String getDepartamento() {
        return this.departamento;
    }
    
    public void setDepartamento(String departamento) {
        this.departamento = departamento;
    }
    public String getProvincia() {
        return this.provincia;
    }
    
    public void setProvincia(String provincia) {
        this.provincia = provincia;
    }
    public String getDistrito() {
        return this.distrito;
    }
    
    public void setDistrito(String distrito) {
        this.distrito = distrito;
    }
    public String getDireccion() {
        return this.direccion;
    }
    
    public void setDireccion(String direccion) {
        this.direccion = direccion;
    }
    public String getReferencia() {
        return this.referencia;
    }
    
    public void setReferencia(String referencia) {
        this.referencia = referencia;
    }
    public String getPersonaDeContacto() {
        return this.personaDeContacto;
    }
    
    public void setPersonaDeContacto(String personaDeContacto) {
        this.personaDeContacto = personaDeContacto;
    }
    public String getTelefonos() {
        return this.telefonos;
    }
    
    public void setTelefonos(String telefonos) {
        this.telefonos = telefonos;
    }
    public String getCorreo() {
        return this.correo;
    }
    
    public void setCorreo(String correo) {
        this.correo = correo;
    }
    public String getWeb() {
        return this.web;
    }
    
    public void setWeb(String web) {
        this.web = web;
    }
    public byte[] getFotoLocal() {
        return this.fotoLocal;
    }
    
    public void setFotoLocal(byte[] fotoLocal) {
        this.fotoLocal = fotoLocal;
    }
    public byte[] getFotoUbicacion() {
        return this.fotoUbicacion;
    }
    
    public void setFotoUbicacion(byte[] fotoUbicacion) {
        this.fotoUbicacion = fotoUbicacion;
    }
    public Integer getFlagPromocion() {
        return this.flagPromocion;
    }
    
    public void setFlagPromocion(Integer flagPromocion) {
        this.flagPromocion = flagPromocion;
    }
    public String getComentarioPerfil() {
        return this.comentarioPerfil;
    }
    
    public void setComentarioPerfil(String comentarioPerfil) {
        this.comentarioPerfil = comentarioPerfil;
    }
    public String getCartaActual() {
        return this.cartaActual;
    }
    
    public void setCartaActual(String cartaActual) {
        this.cartaActual = cartaActual;
    }
    public String getPromocionActual() {
        return this.promocionActual;
    }
    
    public void setPromocionActual(String promocionActual) {
        this.promocionActual = promocionActual;
    }
    public Set getComentarios() {
        return this.comentarios;
    }
    
    public void setComentarios(Set comentarios) {
        this.comentarios = comentarios;
    }
    public Set getTours() {
        return this.tours;
    }
    
    public void setTours(Set tours) {
        this.tours = tours;
    }




}


